-- addTank(sysname, quantity)
-- addCar(sysname, quantity)
-- addHeli(sysname, quantity)
-- addSquad(sysname, quantity)

Reserves = 
{
		aleppo_border = function()
		addCar("sadko_truck", 2)
		addCar("btr80_base", 2)
		addCar("sadko_cabin", 2)
		addCar("toyota_gun", 2)
		addCar("toyota_40mm", 2)
		addCar("toyota_b10", 2)
		addCar("guntrack_01_b10", 2)
		addSquad("sirian_squad_NDF", 3)
		addSquad("sirian_squad_NDF_rpg", 3)
		addSquad("sirian_squad_NDF_sniper", 3)
		addSquad("sirian_tank_crew_01", 3)
		addSquad("sirian_btr_crew_01", 3)
		addSquad("sirian_squad_NDF_PK", 3)
		addSquad("sirian_squad_pulemet", 3)
		addSquad("sirian_squad_spg", 3)
		addSquad("sirian_squad_tigers", 3)
		addSquad("sirian_squad_leban", 3)
		addCar("guntrack_01_grenade", 2)
		addCar("guntrack_01", 2)
		addCar("guntrack_01_zsu", 2)
		addCar("guntrack_01_grenade_noarm", 2)
		addCar("guntrack_01_noarm", 2)
		addCar("guntrack_01_mlrs", 2)
		addCar("btr70", 2)
		addCar("brdm", 2)
		addCar("ural_cabin", 2)
		addSquad("sirian_squad_stormtroopers", 3)
		addSquad("sirian_squad_osv", 3)
		addSquad("sirian_squad_minomet", 3)
		addSquad("sirian_engineer", 3)
		addTank("t55_arm", 2)
		addTank("t62", 2)
		addTank("t62_arm2", 1)
		addTank("t55", 2)
		addTank("t55_sandbags", 1)
		addTank("t72_base", 1)
		addTank("t72_arm", 3)
		addTank("t90", 1)
		addTank("bmp2", 2)
		addTank("bmp1_base", 2)
		addTank("gvozdika", 2)
		addCar("grad", 2)
		addTank("shilka_base", 2)
		addCar("ural_tanker", 2)

	end,

}